export const MOVIE_ADD_TO_WATCHLIST = "MOVIE_ADD_TO_WATCHLIST";
export const MOVIE_REMOVE_FROM_WATCHLIST = "MOVIE_REMOVE_FROM_WATCHLIST";
export const SET_MOVIES = "SET_MOVIES";
export const SET_ERROR = "SET_ERROR";
export const SET_LOADING = "SET_LOADING";
export const SET_SEARCH_VALUE = "SET SEARCH VALUE";